In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("./employee_attrition.csv")
df.shape

(1470, 35)

In [2]:
df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   object
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   object
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   object
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1470 non-null   int64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1470 non-null   object
 12  HourlyRate                1470 non-null   int64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1470 non-null   object
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1470 non-null   object
 18  MonthlyIncome             1470 non-null   int64
 19  MonthlyRate               1470 non-null   int64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   object
 22  OverTime                  1470 non-null   object
 23  PercentSalaryHike         1470 non-null   int64
 24  PerformanceRating         1470 non-null   int64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(26), object(9)
memory usage: 402.1+ KB

In [4]:
df.describe()

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
count,1470.000000,1470.000000,1470.000000,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,...,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000
mean,36.923810,802.485714,9.192517,2.912925,1.0,1024.865306,2.721769,65.891156,2.729932,2.063946,...,2.712245,80.0,0.793878,11.279592,2.799320,2.761224,7.008163,4.229252,2.187755,4.123129
std,9.135373,403.509100,8.106864,1.024165,0.0,602.024335,1.093082,20.329428,0.711561,1.106940,...,1.081209,0.0,0.852077,7.780782,1.289271,0.706476,6.126525,3.623137,3.222430,3.568136
min,18.000000,102.000000,1.000000,1.000000,1.0,1.000000,1.000000,30.000000,1.000000,1.000000,...,1.000000,80.0,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,30.000000,465.000000,2.000000,2.000000,1.0,491.250000,2.000000,48.000000,2.000000,1.000000,...,2.000000,80.0,0.000000,6.000000,2.000000,2.000000,3.000000,2.000000,0.000000,2.000000
50%,36.000000,802.000000,7.000000,3.000000,1.0,1020.500000,3.000000,66.000000,3.000000,2.000000,...,3.000000,80.0,1.000000,10.000000,3.000000,3.000000,5.000000,3.000000,1.000000,3.000000
75%,43.000000,1157.000000,14.000000,4.000000,1.0,1555.750000,4.000000,83.750000,3.000000,3.000000,...,4.000000,80.0,1.000000,15.000000,3.000000,3.000000,9.000000,7.000000,3.000000,7.000000
max,60.000000,1499.000000,29.000000,5.000000,1.0,2068.000000,4.000000,100.000000,4.000000,5.000000,...,4.000000,80.0,3.000000,40.000000,6.000000,4.000000,40.000000,18.000000,15.000000,17.000000

In [35]:
# Feature 1: Promotion Ratio fraction of time gone without promotion
df['PromotionRatio'] = df['YearsSinceLastPromotion'] / (df['YearsAtCompany'] + 1 )
df

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,PromotionRatio
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,80,0,8,0,1,6,4,0,5,0.000000
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,80,1,10,3,3,10,7,1,7,0.090909
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,80,0,7,3,3,0,0,0,0,0.000000
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,80,0,8,3,3,8,7,3,0,0.333333
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,80,1,6,3,3,2,2,2,2,0.666667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,No,Travel_Frequently,884,Research & Development,23,2,Medical,1,2061,...,80,1,17,3,3,5,2,0,3,0.000000
1466,39,No,Travel_Rarely,613,Research & Development,6,1,Medical,1,2062,...,80,1,9,5,3,7,7,1,7,0.125000
1467,27,No,Travel_Rarely,155,Research & Development,4,3,Life Sciences,1,2064,...,80,1,6,0,3,6,2,0,3,0.000000
1468,49,No,Travel_Frequently,1023,Sales,2,3,Medical,1,2065,...,80,0,17,3,2,9,6,0,8,0.000000
1469,34,No,Travel_Rarely,628,Research & Development,8,3,Medical,1,2068,...,80,0,6,3,4,4,3,1,2,0.200000

In [36]:
# Feature 2: Are they getting paid fairly? IncomePerYearExp
df['IncomePerYearExp'] = (df['MonthlyIncome']) / (df['TotalWorkingYears'] + 1) 
df['IncomePerYearExp']

0       665.888889
1       466.363636
2       261.250000
3       323.222222
4       495.428571
           ...
1465    142.833333
1466    999.100000
1467    877.428571
1468    299.444444
1469    629.142857
Name: IncomePerYearExp, Length: 1470, dtype: float64

In [37]:
# Feature transformation
# Take square root of every single value
df['SqrtTraining'] = df['TrainingTimesLastYear'] ** 0.5
df['SqrtTraining']
df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,PromotionRatio,IncomePerYearExp,SqrtTraining
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,8,0,1,6,4,0,5,0.000000,665.888889,0.000000
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,10,3,3,10,7,1,7,0.090909,466.363636,1.732051
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,7,3,3,0,0,0,0,0.000000,261.250000,1.732051
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,8,3,3,8,7,3,0,0.333333,323.222222,1.732051
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,6,3,3,2,2,2,2,0.666667,495.428571,1.732051

In [38]:
# One hot encoding
df['Department'].value_counts()

Department
Research & Development    961
Sales                     446
Human Resources            63
Name: count, dtype: int64

In [41]:
department_encoded = pd.get_dummies(df['Department'], prefix='Dept')
department_encoded.head()

   Dept_Human Resources  Dept_Research & Development  Dept_Sales
0                 False                        False        True
1                 False                         True       False
2                 False                         True       False
3                 False                         True       False
4                 False                         True       False

In [ ]:
df = pd.concat([df, department_encoded], axis=1)
df

0       Yes
1        No
2       Yes
3       Yes
4        No
       ...
1465     No
1466     No
1467    Yes
1468     No
1469     No
Name: OverTime, Length: 1470, dtype: object

In [45]:
df['OverTime_Yes'] = (df['OverTime'] == 'Yes').astype(int)
df

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,Dept_Human Resources,Dept_Research & Development,Dept_Sales,Dept_Human Resources,Dept_Research & Development,Dept_Sales,Dept_Human Resources,Dept_Research & Development,Dept_Sales,OverTime_Yes
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,False,False,True,False,False,True,False,False,True,1
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,False,True,False,False,True,False,False,True,False,0
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,False,True,False,False,True,False,False,True,False,1
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,False,True,False,False,True,False,False,True,False,1
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,False,True,False,False,True,False,False,True,False,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,No,Travel_Frequently,884,Research & Development,23,2,Medical,1,2061,...,False,True,False,False,True,False,False,True,False,0
1466,39,No,Travel_Rarely,613,Research & Development,6,1,Medical,1,2062,...,False,True,False,False,True,False,False,True,False,0
1467,27,No,Travel_Rarely,155,Research & Development,4,3,Life Sciences,1,2064,...,False,True,False,False,True,False,False,True,False,1
1468,49,No,Travel_Frequently,1023,Sales,2,3,Medical,1,2065,...,False,False,True,False,False,True,False,False,True,0
1469,34,No,Travel_Rarely,628,Research & Development,8,3,Medical,1,2068,...,False,True,False,False,True,False,False,True,False,0

In [46]:
# Binning
age_bins = [18, 25, 35, 45, 55, 100]
age_labels = ['18-25', '26-35', '36-45', '46-55', '56+']

df['AgeGroup'] = pd.cut(df['Age'], bins=age_bins, labels=age_labels)
df

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,Dept_Research & Development,Dept_Sales,Dept_Human Resources,Dept_Research & Development,Dept_Sales,Dept_Human Resources,Dept_Research & Development,Dept_Sales,OverTime_Yes,AgeGroup
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,False,True,False,False,True,False,False,True,1,36-45
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,True,False,False,True,False,False,True,False,0,46-55
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,True,False,False,True,False,False,True,False,1,36-45
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,True,False,False,True,False,False,True,False,1,26-35
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,True,False,False,True,False,False,True,False,0,26-35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,No,Travel_Frequently,884,Research & Development,23,2,Medical,1,2061,...,True,False,False,True,False,False,True,False,0,36-45
1466,39,No,Travel_Rarely,613,Research & Development,6,1,Medical,1,2062,...,True,False,False,True,False,False,True,False,0,36-45
1467,27,No,Travel_Rarely,155,Research & Development,4,3,Life Sciences,1,2064,...,True,False,False,True,False,False,True,False,1,26-35
1468,49,No,Travel_Frequently,1023,Sales,2,3,Medical,1,2065,...,False,True,False,False,True,False,False,True,0,46-55
1469,34,No,Travel_Rarely,628,Research & Development,8,3,Medical,1,2068,...,True,False,False,True,False,False,True,False,0,26-35

In [48]:
df['AgeGroup'].value_counts()

AgeGroup
26-35    606
36-45    468
46-55    226
18-25    115
56+       47
Name: count, dtype: int64

In [55]:
# Normalizing
# df['MonthlyIncome'].min()
# df['MonthlyIncome'].max()
from sklearn.preprocessing import MinMaxScaler

minmax_scaler = MinMaxScaler()

df['Income_Normalized'] = minmax_scaler.fit_transform(df[['MonthlyIncome']])
df

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,Dept_Sales,Dept_Human Resources,Dept_Research & Development,Dept_Sales,Dept_Human Resources,Dept_Research & Development,Dept_Sales,OverTime_Yes,AgeGroup,Income_Normalized
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,True,False,False,True,False,False,True,1,36-45,0.262454
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,False,False,True,False,False,True,False,0,46-55,0.217009
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,False,False,True,False,False,True,False,1,36-45,0.056925
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,False,False,True,False,False,True,False,1,26-35,0.100053
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,False,False,True,False,False,True,False,0,26-35,0.129489
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,No,Travel_Frequently,884,Research & Development,23,2,Medical,1,2061,...,False,False,True,False,False,True,False,0,36-45,0.082254
1466,39,No,Travel_Rarely,613,Research & Development,6,1,Medical,1,2062,...,False,False,True,False,False,True,False,0,36-45,0.472986
1467,27,No,Travel_Rarely,155,Research & Development,4,3,Life Sciences,1,2064,...,False,False,True,False,False,True,False,1,26-35,0.270300
1468,49,No,Travel_Frequently,1023,Sales,2,3,Medical,1,2065,...,True,False,False,True,False,False,True,0,46-55,0.230700
1469,34,No,Travel_Rarely,628,Research & Development,8,3,Medical,1,2068,...,False,False,True,False,False,True,False,0,26-35,0.178778