# Titanic Data Explorer - Guided Practice

## Unit 2, Day 2
**Instructor:** Abishek Ganesh

---

## How This Notebook Works

**Part A: Instructor-Led Walkthrough**  
We'll work through these examples together as a class. Follow along and run each cell with me.

**Part B: Breakout Room Exercises**  
You'll work in groups to complete these exercises. Talk through the problems together!

---

### Today's Skills
By the end of this notebook, you will be able to:
1. Load a CSV file into a Pandas DataFrame
2. Explore and understand your data
3. Select specific columns and rows
4. Filter data based on conditions
5. Perform basic calculations on your data

---

# Part A: Instructor-Led Walkthrough

Follow along with Abishek as we work through these examples together.

## A.1 - Loading Data

First, we import our libraries and load the Titanic dataset.

In [2]:
# Import our data science libraries
import numpy as np
import pandas as pd

print("Libraries imported successfully!")

Libraries imported successfully!

In [5]:
# Load the Titanic dataset into a DataFrame
df = pd.read_csv('./titanic.csv')

# Quick check - what's the shape?
print(f"Dataset loaded! Shape: {df.shape}")
print(f"That's {df.shape[0]} rows and {df.shape[1]} columns")

Dataset loaded! Shape: (891, 12)
That's 891 rows and 12 columns

In [8]:
# Look at the first 5 rows
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

## A.2 - Exploring Data

Before doing anything else, we need to understand what data we have.

In [9]:
# info() shows columns, data types, and non-null counts
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [10]:
# describe() gives quick statistics on numerical columns
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [13]:
# isnull().sum() counts missing values in each column
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

## A.3 - Selecting Columns

We can grab specific columns from our DataFrame.

In [20]:
# Select a SINGLE column with single brackets
# This returns a Series (like a single column)
df['Name'].head()
df_new = df[['Name', 'Age', 'Fare']]
df_new[df_new['Age'] > 70]

                                     Name   Age     Fare
96              Goldschmidt, Mr. George B  71.0  34.6542
116                  Connors, Mr. Patrick  70.5   7.7500
493               Artagaveytia, Mr. Ramon  71.0  49.5042
630  Barkworth, Mr. Algernon Henry Wilson  80.0  30.0000
851                   Svensson, Mr. Johan  74.0   7.7750

In [15]:
# Select MULTIPLE columns with double brackets
# This returns a DataFrame (a mini-table)
df[['Name', 'Age', 'Fare']].head()

                                                Name   Age     Fare
0                            Braund, Mr. Owen Harris  22.0   7.2500
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0  71.2833
2                             Heikkinen, Miss. Laina  26.0   7.9250
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0  53.1000
4                           Allen, Mr. William Henry  35.0   8.0500

## A.4 - Selecting Rows

We use `iloc` to select rows by their position (index number).

In [16]:
# Get a single row (the first passenger, index 0)
df.iloc[0]

PassengerId                          1
Survived                             0
Pclass                               3
Name           Braund, Mr. Owen Harris
Sex                               male
Age                               22.0
SibSp                                1
Parch                                0
Ticket                       A/5 21171
Fare                              7.25
Cabin                              NaN
Embarked                             S
Name: 0, dtype: object

In [17]:
# Get a range of rows (first 5 passengers)
df.iloc[0:5]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

## A.5 - Filtering Data

This is where Pandas gets powerful! We can filter rows based on conditions.

In [21]:
# Filter for passengers who survived (Survived == 1)
survivors = df[df['Survived'] == 1]

print(f"Total passengers: {len(df)}")
print(f"Survivors: {len(survivors)}")
survivors.head()

Total passengers: 891
Survivors: 342

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [22]:
# Filter for female passengers
females = df[df['Sex'] == 'female']

print(f"Female passengers: {len(females)}")
females.head()

Female passengers: 314

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

## A.6 - Basic Operations

We can perform calculations on our data.

In [23]:
# Calculate the average fare
avg_fare = df['Fare'].mean()
print(f"Average fare: ${avg_fare:.2f}")

Average fare: $32.20

In [24]:
# Count total survivors using sum()
# Since Survived is 0 or 1, summing gives us the count!
total_survivors = df['Survived'].sum()
print(f"Total survivors: {total_survivors}")

Total survivors: 342

In [25]:
# Count with a filter using len()
female_count = len(df[df['Sex'] == 'female'])
print(f"Number of female passengers: {female_count}")

Number of female passengers: 314

---

# Part B: Breakout Room Exercises

Now it's your turn! Work with your group to complete these exercises.

**Important:** Talk through the problems together. If you get stuck, discuss with your teammates before asking for help.

---

## Section 1: Load & Explore (Warm-Up)

Let's start fresh and load the data into a new variable.

### Exercise 1.1
Load the Titanic dataset into a DataFrame called `df_titanic`

In [35]:
# Your code here
df_titanic = pd.read_csv('./titanic.csv')

### Exercise 1.2
How many rows and columns are in the dataset? Use `.shape`

In [36]:
# Your code here
df_titanic.shape

(891, 12)

### Exercise 1.3
What are the column names? Use `.columns`

In [42]:
# Your code here
idx = df_titanic.columns
for i in idx:
    print(i)

PassengerId
Survived
Pclass
Name
Sex
Age
SibSp
Parch
Ticket
Fare
Cabin
Embarked

### Exercise 1.4
How many missing values are in the 'Age' column?

In [44]:
# Your code here
int(df_titanic['Age'].isnull().sum())

177

### Checkpoint 1
Run this cell to check your answers!

In [45]:
# Checkpoint 1 - Run this to verify your work
print("Checking your answers...")
print()

# Check that df_titanic exists and has correct shape
assert 'df_titanic' in dir(), "Did you create a variable called df_titanic?"
assert df_titanic.shape == (891, 12), f"Shape should be (891, 12), got {df_titanic.shape}"
print("✅ df_titanic loaded correctly!")
print(f"   Rows: 891")
print(f"   Columns: 12")
print(f"   Missing Age values: 177")

Checking your answers...

✅ df_titanic loaded correctly!
   Rows: 891
   Columns: 12
   Missing Age values: 177

---

## Section 2: Selecting Columns

Practice grabbing specific columns from your DataFrame.

### Exercise 2.1
Select just the 'Age' column and display the first 10 values

In [96]:
# Your code here
df_titanic['Age'].head(10)
# df_titanic['Age'].iloc[10:20]

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5     NaN
6    54.0
7     2.0
8    27.0
9    14.0
Name: Age, dtype: float64

### Exercise 2.2
Select just the 'Fare' column and display the first 5 values

In [49]:
# Your code here
df_titanic['Fare'].head()

0     7.2500
1    71.2833
2     7.9250
3    53.1000
4     8.0500
Name: Fare, dtype: float64

### Exercise 2.3
Select the 'Name', 'Sex', and 'Survived' columns together (as a mini DataFrame). Display the first 5 rows.

In [51]:
# Your code here
df_titanic[['Name', 'Sex', 'Survived']].head()

                                                Name     Sex  Survived
0                            Braund, Mr. Owen Harris    male         0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female         1
2                             Heikkinen, Miss. Laina  female         1
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female         1
4                           Allen, Mr. William Henry    male         0

### Exercise 2.4
Create a new DataFrame called `passenger_info` with these columns: Name, Age, Sex, Pclass

In [53]:
# Your code here
passenger_info = df_titanic[['Name', 'Age', 'Sex', 'Pclass']]
passenger_info

                                                  Name   Age     Sex  Pclass
0                              Braund, Mr. Owen Harris  22.0    male       3
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0  female       1
2                               Heikkinen, Miss. Laina  26.0  female       3
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0  female       1
4                             Allen, Mr. William Henry  35.0    male       3
..                                                 ...   ...     ...     ...
886                              Montvila, Rev. Juozas  27.0    male       2
887                       Graham, Miss. Margaret Edith  19.0  female       1
888           Johnston, Miss. Catherine Helen "Carrie"   NaN  female       3
889                              Behr, Mr. Karl Howell  26.0    male       1
890                                Dooley, Mr. Patrick  32.0    male       3

[891 rows x 4 columns]

### Checkpoint 2
Run this cell to check your answers!

In [54]:
# Checkpoint 2 - Run this to verify your work
print("Checking your answers...")
print()

assert 'passenger_info' in dir(), "Did you create a variable called passenger_info?"
assert passenger_info.shape == (891, 4), f"passenger_info shape should be (891, 4), got {passenger_info.shape}"
assert list(passenger_info.columns) == ['Name', 'Age', 'Sex', 'Pclass'], "Columns should be Name, Age, Sex, Pclass"

print("✅ passenger_info created correctly!")
print(f"   Shape: {passenger_info.shape}")
print()
print("Great job on Section 2!")

Checking your answers...

✅ passenger_info created correctly!
   Shape: (891, 4)

Great job on Section 2!

---

## Section 3: Selecting Rows

Practice using `iloc` to grab specific rows.

### Exercise 3.1
Get the 10th passenger's information using `iloc` (remember: Python starts counting at 0!)

In [56]:
# Your code here
df_titanic.iloc[9]

PassengerId                                     10
Survived                                         1
Pclass                                           2
Name           Nasser, Mrs. Nicholas (Adele Achem)
Sex                                         female
Age                                           14.0
SibSp                                            1
Parch                                            0
Ticket                                      237736
Fare                                       30.0708
Cabin                                          NaN
Embarked                                         C
Name: 9, dtype: object

### Exercise 3.2
Get passengers at rows 20 through 24 (5 passengers total)

In [58]:
# Your code here
df_titanic.iloc[19:24]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C
20,21,0,2,"Fynney, Mr. Joseph J",male,35.0,0,0,239865,26.0000,NaN,S
21,22,1,2,"Beesley, Mr. Lawrence",male,34.0,0,0,248698,13.0000,D56,S
22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15.0,0,0,330923,8.0292,NaN,Q
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S

### Exercise 3.3
Get the LAST passenger's information using `iloc`

In [97]:
# Your code here
df_titanic.iloc[[-1]]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

### Exercise 3.4
Get the first 3 rows and only columns at positions 1, 3, and 4 (Survived, Name, Sex)

In [98]:
# Your code here
# [['Survived', 'Name', 'Sex']]
df_titanic.iloc[0:3, [1,3,4]]

   Survived                                               Name     Sex
0         0                            Braund, Mr. Owen Harris    male
1         1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female
2         1                             Heikkinen, Miss. Laina  female

### Checkpoint 3
Run this cell to check your answers!

In [99]:
# Checkpoint 3 - Run this to verify your work
print("Checking your answers...")
print()

# Check the 10th passenger (index 9)
tenth = df_titanic.iloc[9]
print(f"✅ The 10th passenger is: {tenth['Name']}")

# Check the last passenger
last = df_titanic.iloc[-1]
print(f"✅ The last passenger is: {last['Name']}")
print()
print("Great job on Section 3!")

Checking your answers...

✅ The 10th passenger is: Nasser, Mrs. Nicholas (Adele Achem)
✅ The last passenger is: Dooley, Mr. Patrick

Great job on Section 3!

---

## Section 4: Filtering Data

This is where Pandas really shines! Filter your data based on conditions.

### Exercise 4.1
Find all passengers who survived (Survived == 1). How many are there?

In [66]:
# Your code here
len(df_titanic[df_titanic['Survived'] == 1])

342

### Exercise 4.2
Find all female passengers. How many are there?

In [68]:
# Your code here
len(df_titanic[df_titanic['Sex'] == 'female'])

314

### Exercise 4.3
Find all first class passengers (Pclass == 1). How many are there?

In [69]:
# Your code here
len(df_titanic[df_titanic['Pclass'] == 1])

216

### Exercise 4.4
Find all passengers under 18 years old (children). How many?

In [70]:
# Your code here
len(df_titanic[df_titanic['Age'] < 18])

113

### Exercise 4.5
Find all passengers who paid more than $50 for their fare. How many?

In [71]:
# Your code here
len(df_titanic[df_titanic['Fare'] > 50])

160

### Checkpoint 4
Run this cell to check your answers!

In [72]:
# Checkpoint 4 - Run this to verify your work
print("Checking your answers...")
print()

survivors_count = len(df_titanic[df_titanic['Survived'] == 1])
females_count = len(df_titanic[df_titanic['Sex'] == 'female'])
first_class_count = len(df_titanic[df_titanic['Pclass'] == 1])
children_count = len(df_titanic[df_titanic['Age'] < 18])
high_fare_count = len(df_titanic[df_titanic['Fare'] > 50])

print(f"✅ Survivors: {survivors_count}")
print(f"✅ Female passengers: {females_count}")
print(f"✅ First class passengers: {first_class_count}")
print(f"✅ Children (under 18): {children_count}")
print(f"✅ Passengers who paid > $50: {high_fare_count}")
print()
print("Great job on Section 4!")

Checking your answers...

✅ Survivors: 342
✅ Female passengers: 314
✅ First class passengers: 216
✅ Children (under 18): 113
✅ Passengers who paid > $50: 160

Great job on Section 4!

---

## Section 5: Basic Operations

Let's do some calculations on our data!

### Exercise 5.1
What is the average age of all passengers? Use `.mean()`

In [103]:
# Your code here
print(f"Avg age: {float(df_titanic['Age'].mean()):.2f}")

Avg age: 29.70

### Exercise 5.2
What is the average fare paid?

In [76]:
# Your code here
float(df_titanic['Fare'].mean())

32.204207968574636

### Exercise 5.3
What is the maximum fare anyone paid? Use `.max()`

In [78]:
# Your code here
float(df_titanic['Fare'].max())

512.3292

### Exercise 5.4
What is the total number of survivors? Use `.sum()` on the Survived column

In [80]:
# Your code here
int(df_titanic['Survived'].sum())

342

### Exercise 5.5
What percentage of passengers survived? 

Think about it: The Survived column has 0s and 1s. What does the mean of 0s and 1s tell you?

In [104]:
# Your code here
percentage_survived = len(df_titanic[df_titanic['Survived'] == 1]) / len(df_titanic)
round(percentage_survived * 100, 2)

38.38

### Checkpoint 5
Run this cell to check your answers!

In [86]:
# Checkpoint 5 - Run this to verify your work
print("Checking your answers...")
print()

avg_age = df_titanic['Age'].mean()
avg_fare = df_titanic['Fare'].mean()
max_fare = df_titanic['Fare'].max()
total_survivors = df_titanic['Survived'].sum()
survival_rate = df_titanic['Survived'].mean() * 100

print(f"✅ Average age: {avg_age:.1f} years")
print(f"✅ Average fare: ${avg_fare:.2f}")
print(f"✅ Maximum fare: ${max_fare:.2f}")
print(f"✅ Total survivors: {total_survivors}")
print(f"✅ Survival rate: {survival_rate:.1f}%")
print()
print("Great job on Section 5!")

Checking your answers...

✅ Average age: 29.7 years
✅ Average fare: $32.20
✅ Maximum fare: $512.33
✅ Total survivors: 342
✅ Survival rate: 38.4%

Great job on Section 5!

---

## Section 6: Putting It Together

These exercises combine multiple skills. Work through them step by step!

### Exercise 6.1
Find the average age of survivors only.

**Steps:**
1. Filter for survivors
2. Calculate the mean of the Age column

In [105]:
# Your code here
survived_age = df_titanic[df_titanic['Survived'] == 1]
round(float(survived_age['Age'].mean()), 2)

28.34

### Exercise 6.2
Find the average fare paid by first class passengers.

**Steps:**
1. Filter for Pclass == 1
2. Calculate the mean of the Fare column

In [107]:
# Your code here
fares_df = df_titanic[df_titanic['Pclass'] == 1]
round(float(fares_df['Fare'].mean()), 2)

84.15

### Exercise 6.3
Count how many female passengers survived.

**Steps:**
1. Filter for female passengers
2. From those, filter for survivors (or combine both conditions)
3. Count with `len()`

In [94]:
# Your code here
len(df_titanic[(df_titanic['Sex'] == 'female') & (df_titanic['Survived'] == 1)])

233

### Final Checkpoint
Run this cell to check your final answers!

In [95]:
# Final Checkpoint - Run this to verify your work
print("Checking your answers...")
print()

# Calculate expected answers
survivors = df_titanic[df_titanic['Survived'] == 1]
avg_age_survivors = survivors['Age'].mean()

first_class = df_titanic[df_titanic['Pclass'] == 1]
avg_fare_first = first_class['Fare'].mean()

female_survivors = df_titanic[(df_titanic['Sex'] == 'female') & (df_titanic['Survived'] == 1)]
female_survivor_count = len(female_survivors)

print(f"✅ Average age of survivors: {avg_age_survivors:.1f} years")
print(f"✅ Average fare for first class: ${avg_fare_first:.2f}")
print(f"✅ Female survivors: {female_survivor_count}")
print()
print("="*50)
print("🎉 Congratulations! You've completed all exercises!")
print("="*50)

Checking your answers...

✅ Average age of survivors: 28.3 years
✅ Average fare for first class: $84.15
✅ Female survivors: 233

==================================================
🎉 Congratulations! You've completed all exercises!
==================================================

---

## Wrap-Up

**Today you learned how to:**
- Load CSV data into a Pandas DataFrame
- Explore data with `head()`, `info()`, `describe()`, `isnull()`
- Select columns (single and multiple)
- Select rows with `iloc`
- Filter data with conditions
- Perform calculations with `mean()`, `sum()`, `max()`

**These are the core skills you'll use in almost every data science project!**

---

*Great work today!*